- name: db instalation 
  hosts: mysql
  become: yes
  tasks: 
    - name: Install MySQL
      ansible.builtin.dnf:
        name: mysql-server
        state: present
    
    - name: mysql service 
      ansible.builtin.service:
        name: mysqld
        enabled: yes
        state: started
    
    - name: set password
      ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@1
          
