- name: frontend instalation 
  hosts: frontend
  become: yes
  tasks: 
  - name: install nginx
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: enable and start nginx
    ansible.builtin.service:
      name: nginx
      enabled: yes
      state: started

  - name: Remove html
    ansible.builtin.command: rm -rf /usr/share/nginx/html/*
    
  - name: Remove the default content
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: absent

  - name: Download the frontend
    ansible.builtin.get_url:
      url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /tmp/frontend.zip

  - name: add directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Unarchive frontend files
    ansible.builtin.unarchive:
      src: /path/to/frontend.zip
      dest: /tmp/
      remote_src: yes


  - name: Expense frontend Service copy 
    ansible.builtin.copy:
      src: expense.conf
      path: /etc/nginx/default.d/expense.conf

  - name: restart nginx
    ansible.builtin.service:
      name: frontend
      state: restarted
